homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 30.2936
  longitude: 120.1614
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 14
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# for iOS client
ios:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google
#  - platform: microsoft
#    api_key: f10f8dcc1fa44a58a11e3b7f61ee793c

# Cloud
cloud:

# Configurator UI
#panel_iframe:
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: http://deb08:3218

# Customized 485 lights
#light:
#  - platform: 485_lights
#    host: HOST_HERE
#    username: USERNAME_HERE
#    password: PASSWORD_HERE_OR_secrets.yaml
#light:
#  - platform: velbus
#    devices:
#       - name: Switch 1
#         type: single
#         module: 0xda
#         channel: 4
#       - name: Switch 2
#         type: double
#         module: 0xbc
#         open_channel: 1
#         close_channel: 2


laite:
   port: '/dev/ttyUSB0'
switch: !include laite.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
    default: critical
    logs:
        custom_components.laite: debug
        custom_components.switch.laite: debug

